SELECT * FROM lmman_practice.customers

--customer_fname,customer_lname,customer_id

select * from lmman_practice.orders
--order_customer_id,order_date
--Get order count per customer for the month of 2014 January.
select cus.customer_id, ord.order_date, cus.customer_fname, cus.customer_lname, count(cus.customer_id) as customer_order_count
from lmman_practice.customers cus left join lmman_practice.orders ord
on cus.customer_id = ord.order_customer_id
where to_char(ord.order_date, 'yyyy-MM-dd') like '2014-01%'
group by cus.customer_id,ord.order_date
order by customer_order_count desc, cus.customer_id

select count(1) from
(
select cus.customer_id, ord.order_date, cus.customer_fname, cus.customer_lname, count(cus.customer_id) as customer_order_count
from lmman_practice.customers cus left join lmman_practice.orders ord
on cus.customer_id = ord.order_customer_id
where to_char(ord.order_date, 'yyyy-MM-dd') like '2014-01%'
group by cus.customer_id,ord.order_date
order by customer_order_count desc, cus.customer_id
) excercise_1


---Get the customer details who have not placed any order for the month of 2014 January.

select * from lmman_practice.customers

--order_customer_id,employee_id

select distinct(order_status) from lmman_practice.orders
--


select *
from lmman_practice.customers cus left join lmman_practice.orders ord
on cus.customer_id = ord.order_customer_id
where to_char(ord.order_date, 'yyyy-MM-dd') like '2014-01%' and ord.order_status in ('ON_HOLD','CANCELED')
order by cus.customer_id 


select count(*) from (
select *
from lmman_practice.customers cus left join lmman_practice.orders ord
on cus.customer_id = ord.order_customer_id
where to_char(ord.order_date, 'yyyy-MM-dd') like '2014-01%' and ord.order_status in ('ON_HOLD','CANCELED')
order by cus.customer_id) exercise_2

--Get the revenue generated by each customer for the month of 2014 January
--revenue -- customer -- 

select * from lmman_practice.order_items --order_item_id, order_item_order_id, order_item_product_id
select * from  lmman_practice.orders --order_id, --order_customer_id
select * from lmman_practice.customers -- customer_id

select cus.customer_id, cus.customer_fname, cus.customer_lname, oi.order_item_subtotal as customer_revenue from
 lmman_practice.customers cus left join lmman_practice.orders ord
 on cus.customer_id = ord.order_customer_id
 left join lmman_practice.order_items oi
 on ord.order_id  = oi.order_item_order_id
 where ord.order_status  in ('COMPLETE', 'CLOSED') and oi.order_item_subtotal > 0
 order by customer_revenue desc, cus.customer_id
 limit 10
 
 select count(*) from (
 select cus.customer_id, cus.customer_fname, cus.customer_lname, oi.order_item_subtotal as customer_revenue from
 lmman_practice.customers cus left join lmman_practice.orders ord
 on cus.customer_id = ord.order_customer_id
 left join lmman_practice.order_items oi
 on ord.order_id  = oi.order_item_order_id
 where ord.order_status  in ('COMPLETE', 'CLOSED') and oi.order_item_subtotal > 0
 order by customer_revenue desc, cus.customer_id
 ) exercise_3

--Get the revenue generated for each category for the month of 2014 January
 
 --revenue --category --timeofday
 
 select * from lmman_practice.categories --category_id, catetory_department_id
 select * from  lmman_practice.order_items --order_item_product_id
-- select * from lmman_practice.orders
 select * from lmman_practice.products --product_id --product_category_id
 
 
 select prod.product_category_id ,prod.product_name, round(sum(oi.order_item_subtotal)) as caterory_revenue  from 
 lmman_practice.products prod left join lmman_practice.order_items oi
 on prod.product_id = oi.order_item_product_id
 left join lmman_practice.categories cat
 on prod.product_category_id = cat.category_id 
 left join lmman_practice.orders ord on
 oi.order_item_id  = ord.order_id
 where ord.order_status in ('COMPLETE','CLOSED') and to_char(ord.order_date, 'yyyy-MM-dd') like '2014-01%'
 group by prod.product_category_id, prod.product_name, cat.category_id
 order by caterory_revenue
 
 ----Get the products for each department --product and department
 
--Tables - departments, categories, products
--
--Data should be sorted in ascending order by department_id
--
--Output should contain all the fields from department and the product count as product_count
 
 
 select * from lmman_practice.department --department_id
 select * from lmman_practice.categories --category_id, category_departmen_id
 select * from lmman_practice.products --product_id, product_category_id
 
 
 select dep.department_name,count(prod.product_name) as number_product, round(sum(prod.product_price)) as total_price from 
 lmman_practice.products prod left join lmman_practice.categories cat
 on prod.product_category_id  = cat.category_id 
 left join lmman_practice.department dep
 on cat.category_department_id  = dep.department_id
group by dep.department_name
 limit 10